name: vint
version: 0.7.1
author: Victor Savkin <vic.savkin@gmail.com>
description: VINT is a framework for writing single-page applications in Dart.
homepage: http://vintdart.com
dev_dependencies:
  unittest: any
  dartmocks: any
  browser: any
